# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing_extensions import Literal, TypeAlias

__all__ = ["ClinicRole"]

ClinicRole: TypeAlias = Literal[
    "Doctor",
    "Physician",
    "Surgeon",
    "Radiologist",
    "Cardiologist",
    "Neurologist",
    "Urologist",
    "Gynecologist",
    "Endocrinologist",
    "Oncologist",
    "Radiation Oncologist",
    "Hematologist",
    "Gastroenterologist",
    "Pulmonologist",
    "Nephrologist",
    "Rheumatologist",
    "Dermatologist",
    "Ophthalmologist",
    "Otolaryngologist",
    "Pediatrician",
    "Obstetrician",
    "Psychiatrist",
    "Anesthesiologist",
    "Emergency Medicine Physician",
    "Family Medicine Physician",
    "Internal Medicine Physician",
    "Pathologist",
    "Nuclear Medicine Physician",
    "Pain Management Specialist",
    "Infectious Disease Specialist",
    "Immunologist",
    "Physician Assistant",
    "Nurse Practitioner",
    "Certified Registered Nurse Anesthetist",
    "Psychologist",
    "Medical Assistant",
    "Scribe",
    "Registered Nurse",
    "Nurse Manager",
    "Patient Care Coordinator",
    "Imaging Technologist",
    "Laboratory Technician",
    "Medical Laboratory Scientist",
    "Pathologists' Assistant",
    "Phlebotomist",
    "Pharmacist",
    "Pharmacy Technician",
    "Physical Therapist",
    "Occupational Therapist",
    "Speech-Language Pathologist",
    "Respiratory Therapist",
    "Nutritionist",
    "Front Desk Operator",
    "Revenue Cycle Manager",
    "Administrative Director",
    "Administrative Assistant",
    "Legal Administrator",
    "IT Administrator",
    "IT Support",
    "Software Engineer",
    "Other",
]
